<a href="https://colab.research.google.com/github/Hsuumyatt/MMDT_T-PY101_2025_Batch02/blob/main/Hsuumyatt/Ex06_Function_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Exercises cover both Exception Handling and variable scopes.


### Q1) Run the following programs, identify and Fix the errors.
Use **exception handling** approach to handle the erros.


In [2]:
#Q1.1) Zero division error
def myfunction(a, b):
    try:
        answer = a / b
        return answer
    except ZeroDivisionError:
        return "Error: Division by zero is not allowed."

# Call the function
print(myfunction(2, 0))

Error: Division by zero is not allowed.


In [10]:
#Q1.2 Name Error
def myfunction2(c):
    try:
        answer = a / c
        return answer
    except NameError:
        return "Error: variable 'a' is not defined."

# Call the function
print(myfunction2(3))

Error: variable 'a' is not defined.


In [11]:
#Q1.3 IndexError
def myfunction3(b):
    mylist = [2, 3, 5, -7, 8, 0]
    idx = 0
    while idx <= 6:   # This will still reach index 6
        try:
            print('Iteration:', idx, mylist[idx] / b)
        except IndexError:
            print("Error: Index out of range.")
        except ZeroDivisionError:
            print("Error: Cannot divide by zero.")
        finally:
            print('Iteration completed')
        idx = idx + 1

In [13]:
#Q1.4 Zero Division Error, Value Error
def divide(a, b):
    try:
        # Convert inputs to numbers if possible
        a = float(a)
        b = float(b)

        result = a / b
        print('The result of division is', result)
        return result

    except ZeroDivisionError:
        print("Error: Cannot divide by zero.")
    except ValueError:
        print("Error: Invalid numeric value.")
    except TypeError:
        print("Error: Unsupported data type.")

In [15]:
#Q1.5 FileNotFoundError
def read_file(filename):
    try:
        with open(filename, 'r') as file1:
            word_string = file1.read()
        print("File reading completed successfully")
        return word_string

    except FileNotFoundError:
        print("Error: The file does not exist.")
    except PermissionError:
        print("Error: You don't have permission to read this file.")

### Q2) Run the following programs and identify the potential errors.
Check the scopes of the variable, and fix it.

In [18]:
def check_rows(grid, expected_numbers):
    """Checks for uniqueness and completeness (1-9) in every row."""
    for i, row in enumerate(grid):
        if set(row) != expected_numbers:
            return False, f"Row {i + 1}: {row}"
    return True, None


def check_cols(grid, expected_numbers, sudoku_size):
    """Checks for uniqueness and completeness (1-9) in every column."""
    for j in range(sudoku_size):
        column = [grid[i][j] for i in range(sudoku_size)]
        if set(column) != expected_numbers:
            return False, f"Column {j + 1}: {column}"
    return True, None


def check_blocks(grid, expected_numbers, sudoku_size):
    """Checks for uniqueness and completeness (1-9) in every 3x3 block."""
    for block_row_start in [0, 3, 6]:
        for block_col_start in [0, 3, 6]:
            block = []
            for i in range(block_row_start, block_row_start + 3):
                for j in range(block_col_start, block_col_start + 3):
                    block.append(grid[i][j])

            if set(block) != expected_numbers:
                return False, f"Block starting at ({block_row_start+1}, {block_col_start+1})"
    return True, None


def is_sudoku_solved(grid):
    """Checks if the given 9x9 grid is a correctly solved Sudoku."""

    sudoku_size = len(grid)

    if sudoku_size != 9 or any(len(row) != 9 for row in grid):
        print("Error: Grid must be exactly 9x9.")
        return False

    expected_numbers = set(range(1, 10))

    # Check Rows
    is_valid, error_info = check_rows(grid, expected_numbers)
    if not is_valid:
        print(f"Mistake found in {error_info}")
        return False

    # Check Columns
    is_valid, error_info = check_cols(grid, expected_numbers, sudoku_size)
    if not is_valid:
        print(f"Mistake found in {error_info}")
        return False

    # Check Blocks
    is_valid, error_info = check_blocks(grid, expected_numbers, sudoku_size)
    if not is_valid:
        print(f"Mistake found in {error_info}")
        return False

    return True


# === Test Code ===
import numpy as np

print("Random Grid:")
grid = np.random.randint(1, 10, (9, 9))
print(grid)
print(is_sudoku_solved(grid.tolist()))

print("\nCorrect Sudoku:")
solved_grid = [
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
]

print(is_sudoku_solved(solved_grid))

Random Grid:
[[9 2 6 9 4 2 6 4 8]
 [7 9 2 3 7 4 3 9 4]
 [5 2 1 7 4 6 4 8 5]
 [3 9 1 7 5 5 1 1 8]
 [8 9 9 9 7 7 5 5 7]
 [6 3 9 4 5 4 3 5 6]
 [5 2 6 2 9 3 7 4 8]
 [5 5 3 2 1 8 6 2 2]
 [7 8 5 4 2 5 8 9 5]]
Mistake found in Row 1: [9, 2, 6, 9, 4, 2, 6, 4, 8]
False

Correct Sudoku:
True
